Blog/urls.py
from django.urls import path
from Blog.views import PostList, PostDetail, likeView, Profile
from . import views

app_name = "Blog"
urlpatterns = [
    path('', PostList.as_view(), name='post-list'),
    path('signin/', views.signin, name="signin"),
    # path('user_login/', views.user_login, name="user_login"),
    path('signup/', views.signup, name="signup"),
    path('user_signup/', views.user_signup, name="user_signup"),
    path('prof/', Profile, name = 'profile'),
    path('detail/<int:pk>/', PostDetail.as_view(), name='post-detail'),
    path('ajax/likes/', likeView, name='like')
]

MyBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .api_routers import router
urlpatterns = [
     path('', include('Blog.urls', namespace='Blog')),
    path('admin/', admin.site.urls),
    path('api/v1/', include(router.urls)),
    path('api/auth/', include('djoser.urls.authtoken'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Blog/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length = 100)
    # author = models.ForeignKey(User, on_delete = models.CASCADE)
    author = models.CharField(max_length = 100)
    description = models.TextField()
    timestamp = models.DateTimeField(default=timezone.now)
    post_image = models.ImageField(upload_to='uploads/')
    likes = models.IntegerField(default=0)
  
    def __str__(self):
        return self.title #this returns the title of the blog post

class Profile(models.Model):
    user = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)
    image = models.ImageField(upload_to = 'uploads', default = "default.png")
    description= models.TextField(blank=True, max_length=100)
    first_name = models.CharField(max_length=64)
    
    def __str__(self):
        return f'{self.user.username} Profile'

#Owned Model
class OwnedModel(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)

    class Meta:
        abstract = True
class Post(OwnedModel):
    title = models.CharField(max_length=100)

Blog/forms.py
from django import forms

class Signin(forms.Form):
    username = forms.CharField(label='', max_length=100)
    password = forms.CharField(max_length=32, widget=forms.PasswordInput, label='Password')
class Signup(forms.Form):
    username = forms.CharField(label='User name', max_length=100)
    password = forms.CharField(max_length=32, widget=forms.PasswordInput,label="Password")

Blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from Blog.models import Post, Profile
from django.http import JsonResponse
from .forms import Signin
from .forms import Signup
# Create your views for the app Logic here.


def index(request):
    username = None
    blog_list = None
    #comment_form = CommentForm()
    if request.user:
        user = request.user
        blog_list = Blog.objects.order_by('-created_date')
        context = {
            'user': user,
            'blog_list':blog_list, 
            'comment_form': comment_form,
            'Blog': Blog
            }
    return render(request,'Blog/base.html',context)
    
def signin(request):
    form = Signin()
    return render(request, 'Blog/signin.html', context={'form': form})

# def user_login(request):
#     if request.method =='POST':
#         # form = SignupForm(request.POST)
#         if form.is_valid():
#             username = form.cleaned_data.get('username')
#             password = form.cleaned_data.get('password')
#             user = authenticate(request, username = username, password = password)
#             print(user)
#             if user is not None:
#                 login(request, user)
#                 return redirect(reverse('index'))
#             else:
#                 return HttpResponse('Invalid log In')
def signup(request):
    form = Signup()
    return render(request, 'Blog/signup.html', context={'form': form})
    #
def user_signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            
            try:
                user_check = User.objects.get(username=username)
                return HttpResponse("User already exists")
            except User.DoesNotExist:

                user = User.objects.create_user(username=username, password=password)
                user.save()
                print(user)
                return redirect(reverse('index'))

class ProfileView(DetailView):
    model = Profile
    
class PostList(ListView):
    model = Post

class PostDetail(DetailView):
    model = Post
def likeView(request):
    if request.method == "GET":
        i = request.GET.get('i', None)
        # p = Post.objects(id=1)
        p = Post.objects.first
        p.likes = p.likes + 1
        p.save()
        data = {'i' : p.likes}
        return JsonResponse(data)

#class ProfileView(DetailView):
    

templates/Blog/post_detail.html
{% extends 'base.html' %}
{% block content %}
<h3 id = "h_id">{{object.title}}</h3><br>
 <h3 id = "h_id">{{object.author}}</h3><br>
<p id ="btext">{{object.description}}</p><br>
<button type="button" class="btn btn-success" onclick="onClickLike()">Like</button>
<p id = "like">{{object.likes}}</p>
Publihed {{object.timestamp}}<br>
<input id = "likes_id" type="hidden" name="name" value="{{object.id}}">
{% endblock %}

templates/Blog/post_list.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    {% for i in object_list %}
<div class="col-6">
<a id= "h_id" href="{% url 'Blog:post-detail' i.id%}">{{i.title}}</a><br>
{% if i.post_image %}
<img height = "150" width = "200" src="{{i.img.url}}" alt="No image">
{% endif %}
</div>
{% endfor %}
</div>
{% endblock %}

templates/Blog/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <img alt="Profile image" class="rounded-circle account-img"  src="{{user.profile.image.url}}" >
            <div class="media-body">
                <h2 class="account-heading">{{ user.username }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>
    </div>
{% endblock content %}

templates/Blog/signin.html
{% extends "base.html" %}
{% block title %} The Sblog {% endblock %}
{% block content %}


<div class="wrapper fadeInDown">
    <div id="formContent">
      <!-- Tabs Titles -->
  
      <!-- Icon -->
      <div class="fadeIn first">
        <i class="far fa-user"></i>
        <!-- <img src="https://www.iconfinder.com/icons/2203549/download/png/32" height="45" id="icon" alt="User Icon" /> -->
      </div>
      
  
      <!-- Login Form -->
      <!-- action = "% url 'user_login' %" -->
      <form action = '' method="POST"> 
        {% csrf_token %}
        <!-- {{form}} -->
        <input type="text" id="login" class="fadeIn second" name="login" placeholder="username">
        <input type="text" id="password" class="fadeIn third" name="login" placeholder="password">
        <input type="submit" class="fadeIn fourth" value="Log In">
      </form>
  
      <!-- Remind Passowrd -->
      <div id="formFooter">
        <a class="underlineHover" href="#">Forgot Password?</a>
      </div>
  
    </div>
  </div>
{% endblock %}

templates/Blog/signup.html
{% extends "base.html" %}
{% block title %} The Sblog {% endblock %}
{% block content %}


<div class="wrapper fadeInDown">
    <div id="formContent">
      <!-- Tabs Titles -->
  
      <!-- Icon -->
      <div class="fadeIn first">
        <i class="far fa-user"></i>
        <!-- <img src="https://www.iconfinder.com/icons/2203549/download/png/32" height="45" id="icon" alt="User Icon" /> -->
      </div>
      
      <form action = '' method="POST"> 
        {% csrf_token %}
        <input type="text" id="login" class="fadeIn second" name="login" placeholder="username">
        <input type="text" id="password" class="fadeIn third" name="login" placeholder="password">
        <input type="submit" class="fadeIn fourth" value="Signup">
      </form>
      <div id="formFooter">
        If already have account &nbsp; &nbsp;<a class="underlineHover" href="{% url 'Blog:signin' %}">Signin?</a> 
      </div>
  
    </div>
  </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
		<!-- CSS -->
	
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
		<!-- jQuery and JS bundle w/ Popper.js -->

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script> -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<link href="{%static 'css/fonts/font-awesome.min.css'%}" rel="stylesheet" type="text/css">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
		<a class="navbar-brand" href="#">MyBlog</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<form class="form-inline my-2 my-lg-0">
				<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
				<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
			</form>  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		  <ul class="navbar-nav mr-auto">
			<li class="nav-item active">
			  <a class="nav-link" href="{% url 'Blog:post-list'%}">Home <span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'Blog:signup' %}">Signup</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'Blog:signin' %}">SignIn</a>
			  </li>
			  <li class="nav-item">
				<a class="nav-link" href="#">About</a>
			  </li>
		  </ul>
		</div>
	  </nav>
	<div class="container">
	{% block content %}
	{% endblock %}
	</div>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="{% static 'js/script.js' %}" type="text/javascript"></script>
	{% block javascript %}
    </script>
	{% endblock %} 
</body>
</html>